on:
  push:
    branches: [ $default-branch ]
    
jobs:
  auto-integration:
    name: Auto integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.MERGE_BYPASS_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: 'develop'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
